project 'XTILogerManager/XTILogerManagerDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'XTILogerManagerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   use_frameworks!

  # Pods for XTILogerManager
#  pod 'SSZipArchive'
#  pod 'PolyvSocketAPI', '~> 0.5.0'
  pod 'XTILogerManager', :path => '../'

end
